
- name: Install nginx
  hosts: domainsecurity
  become: true

  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=present update_cache=true
      notify:
        - start nginx
    - name: Insert Index Page
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        mode: 0644

  handlers:
    - name: start nginx
      service: name=nginx state=started

